language: objective-c

branches:
 only:
 - 3.0-rewrite

xcode_project: UM Liars Dice.xcodeproj
xcode_scheme: UM Liars Dice
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

# script:
# - xctool clean build test -project UMLiarsDice.xcodeproj -scheme "UM Liars Dice"
