language: objective-c

branches:
 only:
 - 3.0-rewrite

xcode_project: UM Liars Dice.xcodeproj
xcode_scheme: UM Liars Dice
osx_image: xcode8
xcode_sdk: iphonesimulator10.0

script:
  -xcodebuild -scheme 'UM Liars Dice' -sdk iphonesimulator CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build test | xcpretty -c
